from __future__ import annotations

import re
from typing import Any

from pydantic import BaseModel, Field

from gadgetforge.catalog import ActionDefinition, get_action, load_catalog
from gadgetforge.catalog import TEMPLATES_DIR


class EnabledAction(BaseModel):
    id: str
    enabled: bool = True
    params: dict[str, Any] = Field(default_factory=dict)


class ComposeRequest(BaseModel):
    actions: list[EnabledAction] = Field(default_factory=list)
    custom_script: str = ""
    header_comment: str = "Generated by AgentBoot GadgetForge"


def _render_template(template_name: str, action_id: str, params: dict[str, Any]) -> str:
    path = TEMPLATES_DIR / template_name
    text = path.read_text(encoding="utf-8")
    text = text.replace("{{ACTION_ID}}", action_id)
    for key, value in params.items():
        if isinstance(value, bool):
            replacement = "true" if value else "false"
        elif isinstance(value, (int, float)):
            replacement = str(value)
        else:
            replacement = str(value).replace("\\", "\\\\").replace("'", "\\'")
        text = text.replace("{{" + key + "}}", replacement)
    remaining = re.findall(r"\{\{(\w+)\}\}", text)
    for key in remaining:
        text = text.replace("{{" + key + "}}", "")
    return text


def compose_script(
    enabled: list[EnabledAction],
    custom_script: str = "",
    auto_bootstrap: bool = True,
) -> str:
    catalog = load_catalog()
    selected_ids = {e.id for e in enabled if e.enabled}

    if auto_bootstrap:
        selected_ids.add("runtime.bootstrap")

    parts: list[str] = [
        "/* AgentBoot composed script — toggle actions via RPC setAction */",
        "'use strict';",
        "",
    ]

    ordered: list[ActionDefinition] = []
    for action in catalog.actions:
        if action.id in selected_ids:
            ordered.append(action)

    for extra_id in sorted(selected_ids - {a.id for a in ordered}):
        action = get_action(extra_id)
        if action:
            ordered.append(action)

    params_by_id = {e.id: e.params for e in enabled}

    for action in ordered:
        params = dict(params_by_id.get(action.id, {}))
        for p in action.parameters:
            if p.key not in params and p.default is not None:
                params[p.key] = p.default
        body = _render_template(action.template, action.id, params)
        parts.append(f"// --- {action.name} ({action.id}) ---")
        parts.append(body)
        parts.append("")

    if custom_script.strip():
        parts.append("// --- custom ---")
        parts.append(custom_script.strip())
        parts.append("")

    return "\n".join(parts)


def action_ids_from_script(script: str) -> list[str]:
    return re.findall(r"// Action: ([\w.]+)", script)
